name: Build and deploy project
on:
  push:
    branches:
      - main
      - cd

jobs:
  submit_build:
    permissions:
      contents: read
    name: Schedule cloud build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Kick off cloud build
        shell: bash
        env:
          SERVICE_ACCOUNT: '${{ secrets.SERVICE_ACCOUNT }}'
          PROJECT_ID: '${{ env.PROJECT_ID }}'
          REGION: '${{ env.REGION }}'
          IMAGE: '${{ env.IMAGE }}'
        run: make cd_build

  run_deploy:
    name: Deploy app to cloud run
    runs-on: ubuntu-latest
    needs:
      - submit_build
    steps:
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to cloud run
        shell: bash
        env:
          SERVICE_ACCOUNT: '${{ secrets.SERVICE_ACCOUNT }}'
          PROJECT_ID: '${{ env.PROJECT_ID }}'
          REGION: '${{ env.REGION }}'
          IMAGE: '${{ env.IMAGE }}'
        run: make cd_deploy
