name: Build and deploy project

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    permissions:
      contents: read
    name: Schedule cloud build and deploy
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT: '${{secrets.SERVICE_ACCOUNT}}'
      PROJECT_ID: '${{vars.PROJECT_ID}}'
      REGION: '${{vars.REGION}}'
      IMAGE: '${{vars.IMAGE}}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{secrets.SERVICE_ACCOUNT}}'

      - name: Kick off cloud build
        shell: bash
        run: make build

      - name: Deploy to cloud run
        shell: bash
        run: make deploy
